### ISSUE TITLE
Career Portal shows blank page

### ISSUE THREAD

**Issue by vsahdev** [opencats/opencats-wordpress-module#2]
Hi All,
I'm experiencing the following issue with OpenCATS-0.9.3-3 in a local install on a Windows 10 machine. I have followed the instructions as per the video and the installation went through fine. 
When logged in as Administrator, I can activate the career portal by checking 'Enable Public Career Portal'. I can also preview the portal in the right hand side of the Templates section. Clicking on the Full Screen Preview button displays the preview screen as expected. but, clicking on the Career Portal URL in the Career Portal Settings section opens a browser tab which remains blank. The same happens if I go to the Careers URL in any other browser. 

Thanks for investigating.

Regards

Vin

**Comment by cptr13** [comment]
Vsahdev.  I have already created this issue in OpenCATS.  This is the OpenCATS-wordpress module github.  If you want, you can go to the issue I created and add a comment that this is happening for you too.  https://github.com/opencats/OpenCATS/issues/216
